---
title: "Beta-Binomial Example"
author: "Amit Patel"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
```

# Beta Binomial Example 

## Main Example 
```{r}
a0 <- 1
b0 <- 1 
n <- 30 
y <- 16 
a <- a0+y
b <- b0+n-y 
c <- 0.3
q <- 0.9
```

```{r}
mean <- a/(a+b)
mode <- (a-1)/(a+b-2)
var <- (a*b)/((a+b+1)*(a+b)^2)
median <- qbeta(p = 0.5, shape1 = a, shape2 = b)
LB <- qbeta(p = 0.025, shape1 = a, shape2 = b)
UB <- qbeta(p = 0.975, shape1 = a, shape2 = b)
Prob <- pbeta(q = c, shape1 = a, shape2 = b, lower.tail = F)
```

### Plot
Run this code in the console then export as 6x8 pdf landscape
```{r}
PT <- signif(qbeta(p = 1-q, shape1 = a, shape2 = b), 2)

post_data <- data.frame(x = seq(0, 1, by = 0.001)) %>%
  mutate(db = dbeta(x,a,b))

plot <- post_data %>% 
  ggplot(aes(x = x, y = db))+
  geom_line() +
  geom_ribbon(data = post_data %>% filter(x >= PT & x <= 1),
              aes(ymin = 0, ymax = db), fill = "#00BFC4" , alpha = 0.5) +
  geom_vline(aes(xintercept = c),  lty = "longdash") +
  annotate("text", x = -0.01 + c, y = 0.1, size = 5, angle = 90, col = "black",
           hjust = 0, label = paste("Target Response Rate:", c)) +
  ggtitle(label = paste("Posterior Distribution ~ Beta(",a, ", ", b,")",
                        sep = "")) +
  labs(x = "Response Rate", y = " ") +
  scale_y_continuous(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0), breaks = seq(0, 1, by = 0.1)) +
  theme(axis.line=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        plot.title = element_text(hjust = 0.5)) 

plot
```

### Plot with Prior 
```{r}
prior_data <- data.frame(x = seq(0, 1, by = 0.001)) %>%
  mutate(db = dbeta(x,a0,b0))

plot_prior <- post_data %>% 
  ggplot(aes(x = x, y = db))+
  geom_line() +
  geom_ribbon(data = post_data %>% filter(x >= PT & x <= 1),
              aes(ymin = 0, ymax = db), fill = "#00BFC4" , alpha = 0.5)+
  geom_line(data = prior_data, aes(x = x, y = db), col = "red" )+
  geom_vline(aes(xintercept = c), lty = "longdash")+
  annotate("text", x = -0.01 + c, y = 0.1, size = 5, angle = 90, col = "black",
           hjust = 0, label = paste("Target Response Rate:", c),) + 
  annotate("text",  x = 0, y = 1.2, size =5, col = "red", hjust = 0,
           label = paste("Prior ~ Beta(", a0, "," , b0, ")", sep =""))+
  annotate("text", x = 0.65, y = 4.4, size = 5, hjust = 0, 
           label = paste("Median = ", round(median*100,1), "%", sep =""))+
  annotate("text", x = 0.65, y = 4.1, size = 5,  hjust = 0, 
           label = paste("95% CrI: (", round(LB*100,1), "%", ", ",
                         round(UB*100,1), "%)", sep =""))+
  annotate("text", x = 0.65, y = 3.8, size = 5,  hjust = 0, 
           label = expression(P(theta >= 0.3) ==  0.997))+
  ggtitle(label = paste("Posterior Distribution ~ Beta(",a, ", ", b,")",
                        sep = "")) +
  labs(x = "Response Rate", y = " ") +
  scale_y_continuous(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0), breaks = seq(0, 1, by = 0.1))+
  theme(axis.line=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        plot.title = element_text(hjust = 0.5)) 

plot_prior
```

### Plot with Sceptical Prior
```{r}
# sceptical prior 
a0 <- 2 
b0 <- 8 
n <- 30 
y <- 16 
a <- a0+y
b <- b0+n-y 
c <- 0.3
q <- 0.9
```

```{r}
mean <- a/(a+b)
mode <- (a-1)/(a+b-2)
var <- (a*b)/((a+b+1)*(a+b)^2)
median <- qbeta(p = 0.5, shape1 = a, shape2 = b)
LB <- qbeta(p = 0.025, shape1 = a, shape2 = b)
UB <- qbeta(p = 0.975, shape1 = a, shape2 = b)
Prob <- pbeta(q = c, shape1 = a, shape2 = b, lower.tail = F)
```

```{r}
PT <- signif(qbeta(p = 1-q, shape1 = a, shape2 = b), 2)

post_data <- data.frame(x = seq(0, 1, by = 0.001)) %>%
  mutate(db = dbeta(x,a,b))

prior_data <- data.frame(x = seq(0, 1, by = 0.001)) %>%
  mutate(db = dbeta(x,a0,b0))

plot_scep <- post_data %>% 
  ggplot(aes(x = x, y = db))+
  geom_line() +
  geom_ribbon(data = post_data %>% filter(x >= PT & x <= 1),
              aes(ymin = 0, ymax = db), fill = "#00BFC4" , alpha = 0.5)+
  geom_line(data = prior_data, aes(x = x, y = db), col = "red" )+
  geom_vline(aes(xintercept = c), lty = "longdash")+
  annotate("text", x = -0.01 + c, y = 0.1, size = 5, angle = 90, col = "black",
           hjust = 0, label = paste("Target Response Rate:", c))+ 
  
  annotate("text",  x = 0, y = 3.8, size =5, col = "red", hjust = 0,
           label = paste("Prior ~ Beta(", a0, "," , b0, ")", sep =""))+
  annotate("text", x = 0.65, y = 4.4, size = 5, hjust = 0, 
           label = paste("Median = ", round(median*100,1), "%", sep =""))+
  annotate("text", x = 0.65, y = 4.1, size = 5,  hjust = 0, 
           label = paste("95% CrI: (", round(LB*100,1), "%", ", ",
                         round(UB*100,1), "%)", sep =""))+
  annotate("text", x = 0.65, y = 3.8, size = 5,  hjust = 0, 
           label = expression(P(theta >= 0.3) ==  0.976))+
  
  ggtitle(label = paste("Posterior Distribution ~ Beta(",a, ", ", b,")",
                        sep = "")) +
  labs(x = "Response Rate", y = " ") +
  scale_y_continuous(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0), breaks = seq(0, 1, by = 0.1))+
  theme(axis.line=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        plot.title = element_text(hjust = 0.5)) 

plot_scep
```
### Plot with Enthusiastic Prior
```{r}
# enthusiastic prior 
a0 <- 7 
b0 <- 3 
n <- 30 
y <- 16 
a <- a0+y
b <- b0+n-y 
c <- 0.3
q <- 0.9
```

```{r}
mean <- a/(a+b)
mode <- (a-1)/(a+b-2)
var <- (a*b)/((a+b+1)*(a+b)^2)
median <- qbeta(p = 0.5, shape1 = a, shape2 = b)
LB <- qbeta(p = 0.025, shape1 = a, shape2 = b)
UB <- qbeta(p = 0.975, shape1 = a, shape2 = b)
Prob <- pbeta(q = c, shape1 = a, shape2 = b, lower.tail = F)
```

```{r}
PT <- signif(qbeta(p = 1-q, shape1 = a, shape2 = b), 2)

post_data <- data.frame(x = seq(0, 1, by = 0.001)) %>%
  mutate(db = dbeta(x,a,b))

prior_data <- data.frame(x = seq(0, 1, by = 0.001)) %>%
  mutate(db = dbeta(x,a0,b0))

plot_enth <- post_data %>% 
  ggplot(aes(x = x, y = db))+
  geom_line() +
  geom_ribbon(data = post_data %>% filter(x >= PT & x <= 1),
              aes(ymin = 0, ymax = db), fill = "#00BFC4" , alpha = 0.5)+
  geom_line(data = prior_data, aes(x = x, y = db), col = "red" )+
  geom_vline(aes(xintercept = c), lty = "longdash")+
  annotate("text", x = -0.01 + c, y = 0.1, size = 5, angle = 90, col = "black",
           hjust = 0, label = paste("Target Response Rate:", c))+ 
  
  annotate("text",  x = 0, y = 0.3, size =5, col = "red", hjust = 0,
           label = paste("Prior ~ Beta(", a0, "," , b0, ")", sep =""))+
  annotate("text", x = 0.65, y = 4.4, size = 5, hjust = 0, 
           label = paste("Median = ", round(median*100,1), "%", sep =""))+
  annotate("text", x = 0.65, y = 4.1, size = 5,  hjust = 0, 
           label = paste("95% CrI: (", round(LB*100,1), "%", ", ",
                         round(UB*100,1), "%)", sep =""))+
  annotate("text", x = 0.65, y = 3.8, size = 5,  hjust = 0, 
           label = expression(P(theta >= 0.3) ==  0.999))+
  
  ggtitle(label = paste("Posterior Distribution ~ Beta(",a, ", ", b,")",
                        sep = "")) +
  labs(x = "Response Rate", y = " ") +
  scale_y_continuous(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0), breaks = seq(0, 1, by = 0.1))+
  theme(axis.line=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        plot.title = element_text(hjust = 0.5)) 

plot_enth
```

### Joint Plot 
Run this code in the console then export as A4 pdf portrait.
```{r}
ggarrange(plot_prior, plot_scep, plot_enth,
          labels = c("Minimally Informative Prior", "Sceptical Prior", 
                     "Enthusiastic Prior"), ncol = 1, nrow = 3, hjust= -0.01)
```

