---
title: "PPoS Example"
author: "Amit Patel"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

```{r}
PPOS <- function(n2, apost, bpost, obj.resp.rate, accept.prob){
  if(n2 == 0){
    PPOS = NA
  }
  else{
    Pr2 <- sapply(0:n2, 
                  function(i) (gamma(apost+bpost)*gamma(n2+1)*gamma(i+apost)*
                                 gamma(n2-i+bpost)) / 
                    (gamma(apost)*gamma(bpost)*gamma(i+1)*gamma(n2-i+1)*
                       gamma(n2+apost+bpost)) )
    
    B <- sapply(0:n2, function(i) 1-pbeta(obj.resp.rate, apost+i, bpost+n2-i))
    
    temp <- cbind(Pr2, B) %>% 
      data.frame() %>% 
      mutate(GO = if_else(B >= accept.prob, 1, 0),
             PPP = Pr2*GO) 
    PPOS = sum(temp$PPP)
  }
  return(list(Data = temp, PPoS = PPOS))
}
```

```{r}
a0 <- 1
b0 <- 1
n <- 30
n1 <- 15
n2 <- n - n1
y <- 8 
apost <- a0+y
bpost <- b0+n1-y 
c <- 0.3
q <- 0.9
```

```{r}
PPoS8 <- PPOS(n2, apost, bpost, c, q)
```

```{r}
PPoS8$Data %>% 
  mutate(Z = 0:n2,
         Pr2 = round(Pr2,4),
         B = round(B,4)) %>% 
  select(Z, everything(), -PPP) %>% 
  kable(format = "latex", booktabs = T, linesep = "", align = 'cccc',
        col.names = c("Z = i", "P(Z = i|x)", "B_i = P(\\theta > 0.3 |x, Z=i",
                      "I_i(B_i > 0.9)"),
        caption = "\\label{tab_etp:bb_ppos_8resp}Predictive probability of success calculations for 8 responses after 15 patients.") %>% 
  cat()
```

```{r}
a0 <- 1
b0 <- 1
n <- 30
n1 <- 15
n2 <- n - n1
y <- 3 
apost <- a0+y
bpost <- b0+n1-y 
c <- 0.3
q <- 0.9
PPoS3 <- PPOS(n2, apost, bpost, c, q)
```

```{r}
a0 <- 1
b0 <- 1
n <- 30
n1 <- 15
n2 <- n - n1
y <- 13 
apost <- a0+y
bpost <- b0+n1-y 
c <- 0.3
q <- 0.9
PPoS13 <- PPOS(n2, apost, bpost, c, q)
```


